---
- name: reboot server
  ansible.builtin.reboot:
    msg: "Rebooting server to apply changes..."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: systemctl is-system-running