---
- name: Provisioning app server
  hosts: app
  strategy: free
  roles:
#    - docker # Not using docker or Kamal right now
    - packages
    - snap
    - ssh
    - firewall
    - net
    - users
#    - traefik # Not using Kamal right now
